export enum ErrorCode {
  PORTFOLIO_NOT_FOUND = 'PORTFOLIO_NOT_FOUND',
  PORTFOLIO_FORBIDDEN = 'PORTFOLIO_FORBIDDEN',
  PORTFOLIO_VALIDATION_FAILED = 'PORTFOLIO_VALIDATION_FAILED',
  PORTFOLIO_ALREADY_DELETED = 'PORTFOLIO_ALREADY_DELETED',
  POSITION_NOT_FOUND = 'POSITION_NOT_FOUND',
  INSTRUMENT_NOT_FOUND = 'INSTRUMENT_NOT_FOUND',
}